# Site settings
title: Andre Le
description: andre le's resume
favicon: /assets/img/icon.JPG
baseurl: https://andre-le.github.io/resume
url: https://andre-le.github.io/resume
rss_url: /pages/atom.xml
#google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Duy Anh Le (Andre Le)
  title: Software Engineer
  address: Oxford, OH, USA
  email: leduyanh1011998@gmail.com
  link: https://andre-le.github.io/portfolio/
  weibo:
  github: andre-le
  linkedin: anh-le-9a908b9a
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Onaclover Technology Joint Stock Company
      location: Hanoi, Vietnam
      title: Intern, Backend Developer
      started: 2017
      duration: Summer 2017
      description: Developed WeFit, an application that help users schedule fitness class and read articles about fitness.<ul><li>Created a CMS written in Elixir for the marketing team to write, edit and publish articles, blogs, etc.<ul><li>Made it more convenient and sufficient for the Marketers; reduced operation time.</li></ul></li><li>Initialized a first step to handle SSO within WeFit productions.<ul><li>Made Google Firebase Authentication a CAS Server, control the flow between Firebase and the apps.</li></ul></li><li>Added the new functionality email verification and forgot password (reset password) using Firebase.</li></ul>
    - work2:
      company: Miami University Housing, Dining, Recreation, and Business Services
      location: Miami University - Oxford, OH, USA
      title: Web Assistant
      started: 2017
      duration: Apr. 2017 - Present
      description: Created more categories page and fixed a lot of bugs in the Miami Bookstore Website.
  educationHistory:
    - education1:
      organization: Miami University
      location: Oxford, Ohio, USA
      degree: Bachelor
      major: Computer Science
      started: 2016
      duration: (2016 - 2020)
      description: <h4><b>GPA:</b> 4.0</h4><p>President's List (all semesters)</p>
  languages:
    - language1:
      name: Vietnamese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: French
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML5/CSS
      percentage: 80%
    - skill2:
      name: Bootstrap
      percentage: 70%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: JQuery
      percentage: 50%
    - skill5:
      name: Java
      percentage: 85%
    - skill6:
      name: Elixir/Phoenix
      percentage: 80%
